<?php

/**
 * @file
 * Contains datefix.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function datefix_element_info_alter(array &$types) {
  $types['datetime']['#process'][] = 'glue_datetime_set_format';
}

/**
 * Element process callback for datetime fields.
 */
function datefix_datetime_set_format($element) {
  // Remove seconds in browsers that support HTML5 type=date.
  $element['time']['#attributes']['step'] = 60;
  return $element;
}