var f=null,g=[],h="",j=0;function k(b){b.returnValue=false;b.a=true;if(!IE()){b.stopPropagation();b.preventDefault()}return false}function m(){var b=document.getElementById("email");b!==null&&b.focus()}
function o(b){var a=IE()?b.keyCode:b.which,c=document.getElementById("text"),d=document.getElementById("field");if(!IE()&&([9,37,39].indexOf(b.keyCode)!=-1||b.altKey||b.b))return true;if(a==13){c.appendChild(document.createElement("br"));j=0;g.push("\n");d.value=h="";return k(b)}else if(BRAILLE()||BRAILLE_KEYBOARD){chr=p(a);g.push(chr);h+=chr;if(BRAILLE())c.innerHTML+=chr;else{b=document.createElement("span");b.className="b"+q(chr);c.appendChild(b)}d.value=h;return true}else switch(a){case 32:f=0;
break;case 70:case 102:f+=32;break;case 68:case 100:f+=16;break;case 83:case 115:f+=8;break;case 74:case 106:f+=4;break;case 75:case 107:f+=2;break;case 76:case 108:f+=1;break;default:return k(b)}return false}
function r(b){var a=IE()?b.keyCode:b.which;if([8,46].indexOf(a)!=-1){a=document.getElementById("text");if(typeof a!="undefined"&&g.length>0){var c=g.pop().charCodeAt(0);if(BRAILLE())a.innerHTML=a.innerHTML.substr(0,c==13?-4:-1);else c!="\n"&&a.removeChild(a.lastChild);if(j-h.length<-1)h=h.substr(0,-1);else if(BRAILLE()){if(BRAILLE()){a=g.lastIndexOf(String.fromCharCode(13));h=c==13?g.slice(a>-1?a:0).join(""):""}}else{for(var d=0,e=-1,i=-1,n=0,l=Math.max(0,a.childNodes.length-83);l<a.childNodes.length;l++)if(a.childNodes[l].nodeName==
"BR"){i=e;e=d;d=l;n+=[" ","\n"].indexOf(g[e])==-1&&e>0}h=g[g.length-1]=="\n"?"":g.slice(e+(e>0)-n).join("");j=i>-1&&g[e]!="\n"?40-e+i+(i>0):0;if(g[d]==" "){c=document.createElement("span");c.className="b0";a.replaceChild(c,a.childNodes[d])}else if(c==13||[" ","\n"].indexOf(g[g.length-1])==-1)a.removeChild(a.lastChild)}document.getElementById("field").value=h}}else if(BRAILLE_KEYBOARD||[37,39,9,112,113,114,115,116,117,118,119,120,121,122,123].indexOf(b.keyCode)!=-1||BRAILLE())return true;else if([0,
68,100,70,102,74,106,75,107,76,108,83,115,32,13].indexOf(a)!=-1)return false;return k(b)}
function p(b){if(BRAILLE_KEYBOARD||BRAILLE()&&b>31){var a=String.fromCharCode(b);if(!BRAILLE()){switch(a){case "`":return"@";case "|":return"\\";case "~":return"^"}}return a}switch(f){case 0:return" ";case 1:return",";case 2:return'"';case 3:return";";case 4:return"@";case 5:return".";case 6:return"^";case 7:return"_";case 8:return"'";case 9:return"-";case 10:return"9";case 11:return"0";case 12:return"/";case 13:return"+";case 14:return">";case 15:return"#";case 16:return"1";case 17:return"5";
case 18:return"3";case 19:return"4";case 20:return"i";case 21:return"[";case 22:return"j";case 23:return"w";case 24:return"2";case 25:return"8";case 26:return"6";case 27:return"7";case 28:return"s";case 29:return"!";case 30:return"t";case 31:return")";case 32:return"a";case 33:return"*";case 34:return"e";case 35:return":";case 36:return"c";case 37:return"%";case 38:return"d";case 39:return"?";case 40:return"k";case 41:return"u";case 42:return"o";case 43:return"z";case 44:return"m";case 45:return"x";
case 46:return"n";case 47:return"y";case 48:return"b";case 49:return"<";case 50:return"h";case 51:return"\\";case 52:return"f";case 53:return"$";case 54:return"g";case 55:return"]";case 56:return"l";case 57:return"v";case 58:return"r";case 59:return"(";case 60:return"p";case 61:return"&";case 62:return"q";case 63:return"="}return null}
function q(b){switch(b){case " ":return 0;case ",":return 1;case '"':return 2;case ";":return 3;case "@":return 4;case ".":return 5;case "^":return 6;case "_":return 7;case "'":return 8;case "-":return 9;case "9":return 10;case "0":return 11;case "/":return 12;case "+":return 13;case ">":return 14;case "#":return 15;case "1":return 16;case "5":return 17;case "3":return 18;case "4":return 19;case "i":return 20;case "[":return 21;case "j":return 22;case "w":return 23;case "2":return 24;case "8":return 25;
case "6":return 26;case "7":return 27;case "s":return 28;case "!":return 29;case "t":return 30;case ")":return 31;case "a":return 32;case "*":return 33;case "e":return 34;case ":":return 35;case "c":return 36;case "%":return 37;case "d":return 38;case "?":return 39;case "k":return 40;case "u":return 41;case "o":return 42;case "z":return 43;case "m":return 44;case "x":return 45;case "n":return 46;case "y":return 47;case "b":return 48;case "<":return 49;case "h":return 50;case "\\":return 51;case "f":return 52;
case "$":return 53;case "g":return 54;case "]":return 55;case "l":return 56;case "v":return 57;case "r":return 58;case "(":return 59;case "p":return 60;case "&":return 61;case "q":return 62;case "=":return 63}return null}
function s(b){var a=IE()?b.keyCode:b.which,c=document.getElementById("field"),d=document.getElementById("text");a=p(a);if(!([9,37,39].indexOf(b.keyCode)!=-1||BRAILLE_KEYBOARD)){document.getElementById("a").innerHTML=f+" "+a;if(!BRAILLE()&&a!==null){g.push(a);h+=a;b=document.createElement("span");b.className="b"+f;document.getElementById("a").innerHTML+=b.className;d.appendChild(b);if(h.length==41&&g.length>39){for(b=d.childNodes.length-1;b>=d.childNodes.length-41;b--)if(d.childNodes[b].className==
"b0"){d.replaceChild(document.createElement("br"),d.childNodes[b]);j=40-h.lastIndexOf(" ");h=h.substr(40-j+1);break}if(b==d.childNodes.length-42){d.insertBefore(document.createElement("br"),d.lastChild);h=a;j=0}}c.value=h}f=null}}function t(b){if((IE()?b.srcElement:b.target).id=="field")document.getElementById("answer").focus();document.getElementById("answer").innerHTML="";document.getElementById("field").focus();return k(b)}
function u(){document.getElementById("field").value="";document.getElementById("hb").value=g.join("");document.getElementById("brailler").submit()}
function v(){for(var b=document.getElementById("real_answer").childNodes,a=1,c=1,d=document.getElementById("your_answer").childNodes,e=0;e<Math.min(b.length,d.length);e++){if(b[e].className!=d[e].className){alert("First error occurred at Line: "+a+" Column: "+c);return}else if(b[e].nodeName=="#text"&&d[e].nodeName=="#text"){for(var i=0;Math.min(b[e].length,d[e].length);i++)if(b[e].nodeValue.charAt(i)!=d[e].nodeValue.charAt(i)){alert("First error occurred at Line: "+a+" Column: "+(i+1));return}if(b[e].length!=
d[e].length){alert("First Error occurred at Line: "+a+" Column: "+J);return}}else if(b[e].nodeName=="BR"){a++;c=0}c++}alert("First error occurred at Line: "+a+" Column: "+c)}if(!Array.prototype.indexOf)Array.prototype.indexOf=function(b,a){var c=this.length;a=Number(a)||0;a=a<0?Math.ceil(a):Math.floor(a);if(a<0)a+=c;for(;a<c;a++)if(a in this&&this[a]===b)return a;return-1};
if(!Array.prototype.lastIndexOf)Array.prototype.lastIndexOf=function(b,a){var c=this.length;a=Number(a)||c-1;a=a<0?Math.ceil(a):Math.floor(a);if(a<0)a=c+a;if(a>=c||a<0)a=c-1;for(;a>0;a--)if(a in this&&this[a]===b)return a;return-1};String.prototype.substr=function(b,a){if(typeof a=="number"&&a===0)return"";a=Number(a)||this.length;var c="";if(b<0)b+=this.length;a=a<0?Math.abs((this.length+a)%this.length):Math.floor(a);for(a=a>this.length-b?this.length-b:a;a>0;a--){c+=this.charAt(b);b++}return c};
window.load=m;window.filter=o;window.getImage=s;window.cancel=r;window.hint=v;window.checkBraille=u;window.clearAnswer=t;