var l=[0,0,0,0,0,0],m=[];function n(a){return document.getElementById(a)}function q(a){a.returnValue=!1;a.cancel=!0;IE()||(a.stopPropagation(),a.preventDefault());return!1}
function r(){var a=l;if(null===a||null===a||-1==a.constructor.toString().indexOf("Array"))return!1;a=a.join("");if(a.match("/[^01]/"))return!1;a=parseInt(a,2);if(isNaN(a)||0>a||63<a)return!1;switch(a){case 0:return" ";case 1:return",";case 2:return'"';case 3:return";";case 4:return"@";case 5:return".";case 6:return"^";case 7:return"_";case 8:return"'";case 9:return"-";case 10:return"9";case 11:return"0";case 12:return"/";case 13:return"+";case 14:return">";case 15:return"#";case 16:return"1";case 17:return"5";
case 18:return"3";case 19:return"4";case 20:return"i";case 21:return"[";case 22:return"j";case 23:return"w";case 24:return"2";case 25:return"8";case 26:return"6";case 27:return"7";case 28:return"s";case 29:return"!";case 30:return"t";case 31:return")";case 32:return"a";case 33:return"*";case 34:return"e";case 35:return":";case 36:return"c";case 37:return"%";case 38:return"d";case 39:return"?";case 40:return"k";case 41:return"u";case 42:return"o";case 43:return"z";case 44:return"m";case 45:return"x";
case 46:return"n";case 47:return"y";case 48:return"b";case 49:return"<";case 50:return"h";case 51:return"\\";case 52:return"f";case 53:return"$";case 54:return"g";case 55:return"]";case 56:return"l";case 57:return"v";case 58:return"r";case 59:return"(";case 60:return"p";case 61:return"&";case 62:return"q";case 63:return"="}}
Array.prototype.indexOf||(Array.prototype.indexOf=function(a,d){var c=this.length,b=Number(d)||0,b=0>b?Math.ceil(b):Math.floor(b);for(0>b&&(b+=c);b<c;b++)if(b in this&&this[b]===a)return b;return-1});Array.prototype.lastIndexOf||(Array.prototype.lastIndexOf=function(a,d){var c=this.length,b=Number(d)||c-1,b=0>b?Math.ceil(b):Math.floor(b);0>b&&(b=c+b);if(b>=c||0>b)b=c-1;for(;0<b;b--)if(b in this&&this[b]===a)return b;return-1});
String.prototype.substr=function(a,d){if("number"==typeof d&&0===d)return"";var c=Number(d)||this.length,b="";0>a&&(a+=this.length);c=0>c?Math.abs((this.length+c)%this.length):Math.floor(c);for(c=c>this.length-a?this.length-a:c;0<c;c--)b+=this.charAt(a),a++;return b};window.load=function(){var a=n("email");null!==a&&a.focus()};
window.filter=function(a){var d=IE()?a.keyCode:a.which,c=n("text"),b=n("field");if(!IE()&&(-1!=[9,37,39].indexOf(a.keyCode)||a.altKey||a.ctrlKey))return!0;if(BRAILLE()){if(13==d)return m.push("\n"),b.value=m.join(""),c.innerHTML+="\n",q(a);if(31<d)return chr=a.charCode?a.charCode:d,chr=String.fromCharCode(chr),m.push(chr),c.innerHTML+=chr,b.value=m.join(""),!0}else switch(d){case 68:case 100:l[1]=1;break;case 70:case 102:l[0]=1;break;case 74:case 106:l[3]=1;break;case 75:case 107:l[4]=1;break;case 76:case 108:l[5]=
1;break;case 83:case 115:l[2]=1;break;case 32:l=[0,0,0,0,0,0];break;case 13:c.innerHTML+="\n",m.push("\n"),b.value=m.join("");default:return q(a)}return!1};window.cancel=function(a){var d=IE()?a.keyCode:a.which,c=n("text");if(-1!=[8,46].indexOf(d))chr=m.pop(),n("field").value=m.join(""),c.innerHTML=c.innerHTML.substr(0,-1);else{if(-1!=[37,39,9,112,113,114,115,116,117,118,119,120,121,122,123].indexOf(a.keyCode)||BRAILLE())return!0;if(-1!=[0,68,100,70,102,74,106,75,107,76,108,83,115,32,13].indexOf(d))return!1}return q(a)};
window.clearAnswer=function(a){"field"==(IE()?a.srcElement:a.target).id&&n("answer").focus();n("answer").innerHTML="";n("field").focus();return q(a)};window.getImage=function(a){var d=IE()?a.keyCode:a.which,c=n("field"),b=n("text"),p=r();-1==[37,39].indexOf(a.keyCode)&&(BRAILLE()||" "==p&&null!==d&&(" "!=p||32!=d)||(m.push(p),b.innerHTML+=p,c.value=m.join("")),l=[0,0,0,0,0,0])};
window.hint=function(){for(var a=n("real_answer").childNodes,d=[],c=[],b=n("your_answer").childNodes,p=0,g={b:[],a:""},h={b:[],a:""},f=0;f<a.length;f++)e=a.item(f),(s="SPAN"==e.nodeName)&&-1<["ab0","ab13","b0","b64"].indexOf(e.className)||"#text"==a[f].nodeName&&/\n/.test(a[f].textContent)?(g.a&&d.push(g),h.b.push(e),h.a+=e.className,g={b:[],a:""}):s&&/b[0-9]/.test(e.className)&&(h.a&&d.push(h),h={b:[],a:""},g.b.push(e),g.a+=e.className);h.a&&d.push(h);g.a&&d.push(g);g={b:[],a:""};h={b:[],a:""};for(f=
0;f<b.length;f++)e=b.item(f),(s="SPAN"==e.nodeName)&&-1<["ab0","ab13","b0","b64"].indexOf(e.className)?(g.a&&c.push(g),h.b.push(e),h.a+=e.className,g={b:[],a:""}):s&&/b[0-9]/.test(e.className)&&(h.a&&c.push(h),h={b:[],a:""},g.b.push(e),g.a+=e.className);h.a&&c.push(h);g.a&&c.push(g);for(f=0;f<c.length;f++)if(!(f in d)||d[f].a!=c[f].a)for(p in c[f].b)c[f].b[p].className+=" error"};window.checkBraille=function(){n("field").value="";n("hb").value=m.join("");n("brailler").submit()};