var g=null,h=[],j="",m=0;function o(a){a.returnValue=false;a.c=true;if(!IE()){a.stopPropagation();a.preventDefault()}return false}function q(){var a=document.getElementById("email");a!==null&&a.focus()}
function r(a){var b=IE()?a.keyCode:a.which,c=document.getElementById("text"),e=document.getElementById("field");if(!IE()&&([9,37,39].indexOf(a.keyCode)!=-1||a.altKey||a.d))return true;if(b==13){c.appendChild(document.createElement("br"));m=0;h.push("\n");e.value=j="";return o(a)}else if(BRAILLE()||BRAILLE_KEYBOARD){chr=s(b);h.push(chr);j+=chr;if(BRAILLE())c.innerHTML+=chr;else{a=document.createElement("span");a.className="b"+t(chr);c.appendChild(a)}e.value=j;return true}else switch(b){case 32:g=0;
break;case 70:case 102:g+=32;break;case 68:case 100:g+=16;break;case 83:case 115:g+=8;break;case 74:case 106:g+=4;break;case 75:case 107:g+=2;break;case 76:case 108:g+=1;break;default:return o(a)}return false}
function w(a){var b=IE()?a.keyCode:a.which;if([8,46].indexOf(b)!=-1){b=document.getElementById("text");if(typeof b!="undefined"&&h.length>0){var c=h.pop().charCodeAt(0);if(BRAILLE())b.innerHTML=b.innerHTML.substr(0,c==13?-4:-1);else c!="\n"&&b.removeChild(b.lastChild);if(m-j.length<-1)j=j.substr(0,-1);else if(BRAILLE()){if(BRAILLE()){b=h.lastIndexOf(String.fromCharCode(13));j=c==13?h.slice(b>-1?b:0).join(""):""}}else{for(var e=0,d=-1,f=-1,n=0,l=Math.max(0,b.childNodes.length-83);l<b.childNodes.length;l++)if(b.childNodes[l].nodeName==
"BR"){f=d;d=e;e=l;n+=[" ","\n"].indexOf(h[d])==-1&&d>0}j=h[h.length-1]=="\n"?"":h.slice(d+(d>0)-n).join("");m=f>-1&&h[d]!="\n"?40-d+f+(f>0):0;if(h[e]==" "){c=document.createElement("span");c.className="b0";b.replaceChild(c,b.childNodes[e])}else if(c==13||[" ","\n"].indexOf(h[h.length-1])==-1)b.removeChild(b.lastChild)}document.getElementById("field").value=j}}else if(BRAILLE_KEYBOARD||[37,39,9,112,113,114,115,116,117,118,119,120,121,122,123].indexOf(a.keyCode)!=-1||BRAILLE())return true;else if([0,
68,100,70,102,74,106,75,107,76,108,83,115,32,13].indexOf(b)!=-1)return false;return o(a)}
function s(a){if(BRAILLE_KEYBOARD||BRAILLE()&&a>31){a=String.fromCharCode(a);if(!BRAILLE())switch(a){case "`":return"@";case "|":return"\\";case "~":return"^"}return a}switch(g){case 0:return" ";case 1:return",";case 2:return'"';case 3:return";";case 4:return"@";case 5:return".";case 6:return"^";case 7:return"_";case 8:return"'";case 9:return"-";case 10:return"9";case 11:return"0";case 12:return"/";case 13:return"+";case 14:return">";case 15:return"#";case 16:return"1";case 17:return"5";case 18:return"3";
case 19:return"4";case 20:return"i";case 21:return"[";case 22:return"j";case 23:return"w";case 24:return"2";case 25:return"8";case 26:return"6";case 27:return"7";case 28:return"s";case 29:return"!";case 30:return"t";case 31:return")";case 32:return"a";case 33:return"*";case 34:return"e";case 35:return":";case 36:return"c";case 37:return"%";case 38:return"d";case 39:return"?";case 40:return"k";case 41:return"u";case 42:return"o";case 43:return"z";case 44:return"m";case 45:return"x";case 46:return"n";
case 47:return"y";case 48:return"b";case 49:return"<";case 50:return"h";case 51:return"\\";case 52:return"f";case 53:return"$";case 54:return"g";case 55:return"]";case 56:return"l";case 57:return"v";case 58:return"r";case 59:return"(";case 60:return"p";case 61:return"&";case 62:return"q";case 63:return"="}return null}
function t(a){switch(a){case " ":return 0;case ",":return 1;case '"':return 2;case ";":return 3;case "@":return 4;case ".":return 5;case "^":return 6;case "_":return 7;case "'":return 8;case "-":return 9;case "9":return 10;case "0":return 11;case "/":return 12;case "+":return 13;case ">":return 14;case "#":return 15;case "1":return 16;case "5":return 17;case "3":return 18;case "4":return 19;case "i":return 20;case "[":return 21;case "j":return 22;case "w":return 23;case "2":return 24;case "8":return 25;
case "6":return 26;case "7":return 27;case "s":return 28;case "!":return 29;case "t":return 30;case ")":return 31;case "a":return 32;case "*":return 33;case "e":return 34;case ":":return 35;case "c":return 36;case "%":return 37;case "d":return 38;case "?":return 39;case "k":return 40;case "u":return 41;case "o":return 42;case "z":return 43;case "m":return 44;case "x":return 45;case "n":return 46;case "y":return 47;case "b":return 48;case "<":return 49;case "h":return 50;case "\\":return 51;case "f":return 52;
case "$":return 53;case "g":return 54;case "]":return 55;case "l":return 56;case "v":return 57;case "r":return 58;case "(":return 59;case "p":return 60;case "&":return 61;case "q":return 62;case "=":return 63}return null}
function x(a){var b=IE()?a.keyCode:a.which,c=document.getElementById("field"),e=document.getElementById("text");b=s(b);if(!([9,37,39].indexOf(a.keyCode)!=-1||BRAILLE_KEYBOARD)){document.getElementById("a").innerHTML=g+" "+b;if(!BRAILLE()&&b!==null){h.push(b);j+=b;a=document.createElement("span");a.className="b"+g;document.getElementById("a").innerHTML+=a.className;e.appendChild(a);if(j.length==41&&h.length>39){for(a=e.childNodes.length-1;a>=e.childNodes.length-41;a--)if(e.childNodes[a].className==
"b0"){e.replaceChild(document.createElement("br"),e.childNodes[a]);m=40-j.lastIndexOf(" ");j=j.substr(40-m+1);break}if(a==e.childNodes.length-42){e.insertBefore(document.createElement("br"),e.lastChild);j=b;m=0}}c.value=j}g=null}}function y(a){if((IE()?a.srcElement:a.target).id=="field")document.getElementById("answer").focus();document.getElementById("answer").innerHTML="";document.getElementById("field").focus();return o(a)}
function z(){document.getElementById("field").value="";document.getElementById("hb").value=h.join("");document.getElementById("brailler").submit()}
function A(){for(var a=document.getElementById("real_answer").childNodes,b=1,c=1,e=document.getElementById("your_answer").childNodes,d=0;d<Math.min(a.length,e.length);d++){if(a[d].className!=e[d].className){alert("First error occurred at Line: "+b+" Column: "+c);return}else if(a[d].nodeName=="#text"&&e[d].nodeName=="#text"){for(var f=0;Math.min(a[d].length,e[d].length);f++)if(a[d].nodeValue.charAt(f)!=e[d].nodeValue.charAt(f)){alert("First error occurred at Line: "+b+" Column: "+(f+1));return}if(a[d].length!=
e[d].length){alert("First Error occurred at Line: "+b+" Column: "+J);return}}else if(a[d].nodeName=="BR"){b++;c=0}c++}alert("First error occurred at Line: "+b+" Column: "+c)}if(!Array.prototype.indexOf)Array.prototype.indexOf=function(a,b){var c=this.length;b=Number(b)||0;b=b<0?Math.ceil(b):Math.floor(b);if(b<0)b+=c;for(;b<c;b++)if(b in this&&this[b]===a)return b;return-1};
if(!Array.prototype.lastIndexOf)Array.prototype.lastIndexOf=function(a,b){var c=this.length;b=Number(b)||c-1;b=b<0?Math.ceil(b):Math.floor(b);if(b<0)b=c+b;if(b>=c||b<0)b=c-1;for(;b>0;b--)if(b in this&&this[b]===a)return b;return-1};String.prototype.substr=function(a,b){if(typeof b=="number"&&b===0)return"";b=Number(b)||this.length;var c="";if(a<0)a+=this.length;b=b<0?Math.abs((this.length+b)%this.length):Math.floor(b);for(b=b>this.length-a?this.length-a:b;b>0;b--){c+=this.charAt(a);a++}return c};
window.load=q;window.filter=r;window.getImage=x;window.cancel=w;window.hint=A;window.checkBraille=z;window.clearAnswer=y;function B(a,b){a=document.getElementById("del");alert(a.selectedIndex);if(a.selectedIndex===0)alert("Please select a "+b+" to delete.");else confirm("Are you sure you want to delete the "+b+'" '+a[a.selectedIndex].text+'"?')&&document.getElementById("form_del").submit()}
function C(a,b){a=document.getElementById(a);b=document.getElementById(b);if(b===null||a===null)alert("Dest or src not found!");else for(var c=0;c<a.options.length;c++)if(a.options[c].selected){document.getElementById("modChanged").value=1;b.options[b.length]=new Option(a.options[c].text,a.options[c].value);for(var e=b.length-1;e>0;e--)if(b.options[e].text<b.options[e-1].text){var d=b.options[e-1];b.options[e-1]=new Option(b.options[e].text,b.options[e].value);b.options[e]=d}a.options[c]=null;c--}}
function D(a,b){a=document.getElementById(a);b=document.getElementById(b);if(b===null||a===null)alert("Dest or src not found!");else{for(var c=JSON.parse(document.getElementById("mods").value),e=-1,d=0;d<c.length&&c[0]!==null;d++)if(c[d]!==null){var f=parseInt(c[d].Value,10);if(isNaN(f)&&f<=e)e=f-1}for(d=0;d<a.options.length;d++)if(a.options[d].selected&&b.id=="courseModules"){document.getElementById("modChanged").value=1;b.options[b.length]=new Option(a.options[d].text,e);c[c.length]={Value:e,modID:a.options[d].value,
Option:a.options[d].text,deleted:0,mode:0,emailResults:0,avail:0,sDate:"",eDate:"",ongoing:0,unit:0,UC:0};e--}else if(a.options[d].selected&&a.id=="courseModules"){document.getElementById("modChanged").value=1;for(f=0;f<c.length;f++)if(c[f].Value==a.options[d].value)c[f].deleted=1;a.options[d]=null;d--}document.getElementById("mods").value=JSON.stringify(c)}}
function E(a,b){var c=JSON.parse(document.getElementById("mods").value);if(c.length>1&&a!=b){for(var e=-1,d=-1,f=0;f<c.length;f++){if(c[f].a==a)e=f;else if(c[f].a==b)d=f;if(e!=-1&&d!=-1)break}if(e==-1||d==-1)alert("Can't swap positions one or both lessons not found.");else{a=c[e];c[e]=c[d];c[d]=a;document.getElementById("mods").value=JSON.stringify(c)}}else a!=b&&alert("Not enought Lesson available to swap")}
function F(a){var b=document.getElementById("courseModules");if([1,-1].indexOf(a)==-1)alert("No direction specified.");else if(b===null)alert("Could not find select box!");else if(b.selectedIndex==-1)alert("No lesson(s) selected.");else if(b.options.length>1){var c=a==1?0:b.length-1;for(document.getElementById("modChanged").value=1;a==1&&c<b.length||a==-1&&c>=0;){if(b.options[c].selected){var e=new Option(b.options[c].text,b.options[c].value,true);if(a===1&&c>0){b.options[c]=new Option(b.options[c-
1].text,b.options[c-1].value);b.options[c-1]=e;E(b.options[c].value,b.options[c-1].value)}else if(a==-1&&c<b.length-1){b.options[c]=new Option(b.options[c+1].text,b.options[c+1].value);b.options[c+1]=e;E(b.options[c+1].value,b.options[c].value)}else if(a==-1&&c==b.length-1||a==1&&c===0)return}a==1?c++:c--}}}
function G(a){a=a===null||typeof a=="undefined"?document:a;var b=a.getElementById("availEvent"),c=a.getElementById("ongoing"),e=a.getElementById("unit"),d=a.getElementById("ongoingAlways"),f=a.getElementById("event"),n=a.getElementById("availDates"),l=a.getElementById("sDate");a=a.getElementById("eDate");if(b.checked===true){f.disabled=c.disabled=e.disabled=d.disabled=false;l.disabled=a.disabled=true}else if(n.checked===true){c.disabled=f.disabled=e.disabled=d.disabled=true;l.disabled=a.disabled=
false}}function H(){for(var a=document.getElementById("courseStudents"),b=0;b<a.options.length;b++)if(!a.options[b].selected)a.options[b].selected=true;document.getElementById("modChanged").value=0;return true}
function I(a){if(document.getElementById("modChanged").value==1&&confirm("This course has been updated do you want to save the changes?")){var b=document.getElementById("modChanged");b.name="redirect";b.value=a.target.activeElement;H();document.getElementById("modify").click();return o(a)}return true}
function K(){window.resizeTo(900,360);window.moveTo(window.screen.width/2-450,window.screen.height/2-180);var a=window.opener.document.getElementById("courseModules"),b=document,c=b.getElementById("hCMID"),e=JSON.parse(window.opener.document.getElementById("mods").value);if(a===null||a.selectedIndex==-1||typeof e!="object"){alert("No Lesson Selected");window.close()}else if(a.selectedIndex>=0&&c.value=="0"){var d=null;for(var f in e)if(e[f]!==null&&e[f].deleted===0&&e[f].Value==a[a.selectedIndex].value){d=
e[f];break}if(d===null){alert("Could not find lesson!");window.close()}else{c.value=d.Value;b.getElementById("h1").innerHTML="Edit Lesson #"+(a.selectedIndex+1)+": "+d.Option;d.aval=typeof d.b!="undefined"?d.avail:0;b.getElementById("availDates").checked=d.avail==1;b.getElementById("availEvent").checked=d.avail==2;G();a=b.getElementById("event");for(f=0;f<a.length;f++)if(a.options[f].value==d.event){a.options[f].selected=true;break}b.getElementById("ongoing").value=parseFloat(d.ongoing)!="NaN"&&d.ongoing>
0?d.ongoing:"";a=b.getElementById("unit");d.unit=typeof d.unit!="undefined"&&d.unit>0&&d.unit<4?d.unit:0;for(f=0;f<a.length;f++)if(a.options[f].value==d.unit)a.options[f].selected=true;b.getElementById("ongoingAlways").checked=parseInt(d.ongoing,10)===0&&d.avail==2;b.getElementById("sDate").value=typeof d.sDate!="undefined"?d.sDate:"";b.getElementById("eDate").value=typeof d.eDate!="undefined"?d.eDate:"";b.getElementById("UC").checked=typeof d.UC!="undefined"&&d.UC===1;a=b.getElementById("mode");
d.mode=typeof d.mode!="undefined"?d.mode:0;for(f=0;f<a.length;f++)if(a.options[f].value==d.mode){a.options[f].selected=true;break}b=b.getElementById("emailResults");d.emailResults=typeof d.emailResults!="undefined"?d.emailResults:0;for(f=0;f<b.length;f++)if(b.options[f].value==d.emailResults)b.options[f].selected=true}}}
function L(){var a=document,b=document.getElementById("hCMID").value;if(b!==0){var c={},e=0,d=a.getElementById("availEvent").checked,f=a.getElementById("UC").checked,n=a.getElementById("ongoing"),l=a.getElementById("unit"),u=a.getElementById("mode"),M=a.getElementById("ongoingAlways").checked,k=a.getElementById("sDate").value,i=a.getElementById("eDate").value,v=a.getElementById("emailResults"),p=JSON.parse(window.opener.document.getElementById("mods").value);a=a.getElementById("event");for(e=0;e<
p.length;e++)if(p[e].Value==b){c=p[e];break}typeof c.modID=="undefined"&&alert("This lesson was not found in the current list of lessons for this course, it cannot be save.");c.avail=d?2:1;if(c.avail==2){c.event=a[a.selectedIndex].value;c.ongoing=M.checked?0:parseFloat(n.value);if(c.ongoing=="NaN"){alert("The amount of time provided for On-demant is not a value decimal number, please fix this.");return}c.unit=l[l.selectedIndex].value;c.sDate=c.eDate=""}else{c.ongoing=c.unit=0;k=k.length>0?new Date(k):
"";if(k!==""&&k!="Invalid Date"){c.sDate=k.getMonth()+1+"/"+k.getDate()+"/";if(IE()&&k.getYear()<2000||!IE())c.sDate+=1900+k.getYear();else if(IE()&&k.getYear()>=2000)c.sDate+=k.getYear()}else{alert("The Start Date is not valid a date, please fix this.");return}i=i.length>0?new Date(i):"";if(i!==""&&i!="Invalid Date"){c.e=i.getMonth()+1+"/"+i.getDate()+"/";if(IE()&&i.getYear()<2000||!IE)c.eDate+=1900+i.getYear();else if(IE()&&i.getYear()>=2000)c.eDate+=i.getYear()}else if(i!==""){alert("The End Date is not valid a date, please fix this.");
return}}c.UC=f;c.mode=u[u.selectedIndex].value;c.emailResults=v[v.selectedIndex].value;p[e]=c;window.opener.document.getElementById("mods").value=JSON.stringify(p);window.opener.document.getElementById("modChanged").value=1;window.close()}}window.saveLesson=L;window.editLesson=K;window.prep=H;window.leave=I;window.update=G;window.moveV=F;window.manLesson=D;window.moveStudent=C;window.checkDel=B;