<?php

/**
 * @file
 * Contains anonpost.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Component\Utility\SafeMarkup;
use Drupal\Core\Config\ConfigFactoryInterface;

/**
 * Implements hook_help().
 */
function anonpost_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the anonpost module.
    case 'help.page.anonpost':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Anonymous posting steps') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function anonpost_theme() {
  return [
    'anonpost' => [
      'render element' => 'children',
    ],
  ];
}
function anonpost_cron()
{
  $old_nodes = \Drupal::service('anonpost.old_nodes')->load();
  foreach ($old_nodes as $node)
  {
  
    
    $node->setPublished(false);
    $node->save();
    $mailManager = \Drupal::service('plugin.manager.mail');
    $module = 'anonpost';
    $key = 'unpublish_job';
    $to = $node->get('field_email')->first()->getValue();
    $params['node_title'] = $node->label();
    $params['message'] = "Your job ad on NERCVE.org, " . $params['node_title'] . " was unpublished after 120 days.  Contact admin@mailer.nercve.org if you wish to re-post a job ad.";
    $langcode = "en";
    $send = true;
    $result = $mailManager->mail($module, $key, $to, $langcode, $params, NULL, $send);
  
  }
}

/**
* Implements hook_mail().
*/
function anonpost_mail($key, &$message, $params) {
  $options = array(
    'langcode' => $message['langcode'],
  );
 
  switch ($key) {
    case 'unpublish_job':
    $message['from'] = \Drupal::config('system.site')->get('mail');
    $message['subject'] = t('Your job ad on NERCVE.org has expired: @title', array('@title' => $params['node_title']), $options);
    $message['body'][] = $params['message'];
    break;
    case 'create_job':
      $message['from'] = \Drupal::config('system.site')->get('mail');
      $message['subject'] = t('Job ad created on NERCVE.org: @title', array('@title' => $params['node_title']), $options);
      $message['body'][] = t('Your job ad, @title was posted to NERCVE.org.  After an adminstrator approves your posting it will be available on our website employment board for 120 days.', array('@title' => $params['node_title']), $options);
      break;
  }
 }

/**
* Implements hook_entity_insert().
*/
function anonpost_entity_insert(Drupal\Core\Entity\EntityInterface $entity) {

  if ($entity->getEntityTypeId() !== 'node' || ($entity->getEntityTypeId() === 'node' && $entity->bundle() !== 'job')) {
  return;
  }
  $config = \Drupal::config('anonpost.customize_messages');
  $mailbody = $config->get('anonmessages');
  $userfirstmailbody = $config->get('firstusermsg');
  $mailManager = \Drupal::service('plugin.manager.mail');
  
  $module = 'anonpost';
  $key = 'create_job';
  $to = $entity->get('field_email')->getString();
  
  $params['message'] = $userfirstmailbody;
  
  $params['node_title'] = $entity->label();
  $langcode = 'und';
  $send = true;
  
  $result = $mailManager->mail($module, $key, $to, $langcode, $params, NULL, $send);
  if ($result['result'] !== true) {
  $message = t('There was a problem sending alert email notification to @email for creating ticket @id.', array('@email' => $to, '@id' => $entity->id()));
  //drupal dblog
  \Drupal::logger('anonpost alert')->error($message);
  return;
  }
  
  $message = t('An email notification has been sent to @email for creating node @id.', array('@email' => $to, '@id' => $entity->id()));
  //drupal dblog
  \Drupal::logger('anonpost alert')->notice($message);
  }
